services:
  scraper:
    build: ./scraper/
    command: sh -c "sleep 10s ; python3 ./reddit_scraper.py"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: db
      REDDIT_CLIENT_ID: DryBYMbMGq11jryH7sCAYQ
      REDDIT_CLIENT_SECRET: SYczKAhPiQWim8scbQaFD4jB0t1Erg
      REDDIT_USER_AGENT: tradingbot:v1.0 (by u/Responsible-Safe3079)
    volumes:
      - .:/usr/app/src
    depends_on:
      - database
  
  sp500:
    build:
      context: ./scraper/
      # dockerfile: Dockerfile
    command: sh -c "sleep 15s ; python3 ./sp500.py"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: db
  
  database:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'

  trading_bot:
      build: ./trading/
      command: sh -c "sleep 20s ; python3 ./trading_algorithm.py"
      environment:
        DB_HOST: database
        DB_USER: root
        DB_PASSWORD: rootpassword
        DB_NAME: db
        ALPACA_API_KEY: PK07EDGVQ81LO97UVFXR
        ALPACA_API_SECRET: ApweWUBamd94diCWAt9ftKC5blCPwHf140H98LKk
      depends_on:
        - database
      volumes:
        - .:/usr/src/app