services:
  scraper:
    build: ./scraper/
    command: sh -c "sleep 10s ; python3 ./reddit_scraper.py"
    env_file:
      - .env
    volumes:
      - .:/usr/app/src
    depends_on:
      - database
  
  sp500:
    build:
      context: ./scraper/
    command: sh -c "sleep 15s ; python3 ./sp500.py"
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
  
  trading_bot:
    build: ./trading/
    command: sh -c "sleep 20s ; python3 ./trading_algorithm.py"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - .:/usr/src/app