services:
  scraper:
    build: ./scraper/
    command: sh -c "sleep 10s ; python3 ./reddit_scraper.py"
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=db
    depends_on:
      - database
  sp500:
    build:
      context: ./scraper/
      dockerfile: Dockerfile
    command: ["python", "./sp500.py"]
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: db
  database:
    build: ./database/
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3306:3306'
